### ISSUE TITLE
POM Issues

### ISSUE THREAD

**Issue by dpmcgarry** [hadrsystems/nics-common#3]
Pom needs to specify character encoding or build can fail:
<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>

Plugin versions are for out of date versions that can't be pulled from maven:
exec.plugin.version needed to be changed to 1.4.0
versions.plugin.version needed to be changed to 1.4

org.codehaus.mojo was missing version tag in XML

**Comment by hadrsystemsteam** [comment]
Addressed in POM updates
